server.port: 8082
#logging.level.org.springframework.cloud.sleuth: DEBUG
logging.level.org.springframework.cloud.client.discovery: DEBUG
logging.level.org.springframework.cloud.loadbalancer: DEBUG
logging.level.org.springframework.cloud.loadbalancer.core: DEBUG
logging.level.com.netflix.discovery: DEBUG
logging.level.reactor.core.publisher: DEBUG


## https://docs.spring.io/spring-cloud/docs/Hoxton.SR9/reference/html/configprops.html
spring:
  application:
    name: frontend-app
  sleuth.sampler.probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411
 
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true
        backoff.enabled: false

      configurations: health-check
      health-check:
        path:
          default: /actuator/health
        refetch-instances: true
        refetch-instances-interval: 1s
      repeat-health-check: true



logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%X{ddd:-},%X{bp:-},%X{bpids:-}] [%X{op:-},%X{chunk:-},%X{i:-}]"


eureka:
  instance:
    registryFetchIntervalSeconds: 1 # client cache
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
##    metadataMap:
##      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
