
## https://resilience4j.readme.io/docs/getting-started-3
#
#
#resilience4j.timelimiter:
#  instances:
#    backend:
#      timeoutDuration: 3s
#      cancelRunningFuture: true
#resilience4j.ratelimiter:
#  instances:
#    backend:
#      limitForPeriod: 3
#      limitRefreshPeriod: 1s
#      timeoutDuration: 5s
#      registerHealthIndicator: true
#      eventConsumerBufferSize: 100
#resilience4j.retry:
#  instances:
#    backend:
#      maxRetryAttempts: 3
#      waitDuration: 5s
#resilience4j.circuitbreaker:
#  instances:
#    backend:
#      registerHealthIndicator: true
#      slidingWindowSize: 10
#      permittedNumberOfCallsInHalfOpenState: 3
#      slidingWindowType: TIME_BASED
#      minimumNumberOfCalls: 20
#      waitDurationInOpenState: 10s
#      failureRateThreshold: 10
#      eventConsumerBufferSize: 10
#      #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate