global:
  scrape_interval: 5s

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
       - targets: ['localhost:9090']
 ##https://github.com/prometheus/prometheus/blob/release-2.24/documentation/examples/prometheus-eureka.yml
   - job_name: 'eureka'
     eureka_sd_configs:
       - server: 'http://192.168.67.1:8761/eureka'


     relabel_configs:

       - source_labels: [__address__, __meta_eureka_app_instance_metadata_prometheus_port]
         action: replace
         regex: ([^:]+)(?::\d+)?;(\d+)
         replacement: $1:$2
         target_label: __address__

       - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
         action: replace
         target_label: __metrics_path__
         regex: (.+)