spring:
  application:
    name: eureka-server 
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    ##waitTimeInMsWhenSyncEmpty: 0
#    ##renewalPercentThreshold: 0
#    response-cache-update-interval-ms: 3000 #https://cloud.spring.io/spring-cloud-static/Dalston.SR5/multi/multi__appendix_compendium_of_configuration_properties.html

  instance:
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
