server.port: 8083
logging.level.org.springframework.cloud.sleuth: DEBUG

spring:
  application:
    name: backend-app
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411