logging.level.org.springframework.cloud.sleuth: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSecond: 3
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
