server.port: 8084
logging.level.org.springframework.cloud.sleuth: DEBUG

spring:
  application:
    name: backendapp2
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411
